# data:
# one of list : “Task01_BrainTumour”, “Task02_Heart”,
# “Task03_Liver”, “Task04_Hippocampus”, “Task05_Prostate”,
# “Task06_Lung”, “Task07_Pancreas”, “Task08_HepaticVessel”,
#  “Task09_Spleen”, “Task10_Colon”.
task: “Task06_Lung”
root_dir: "./data"

# experiment:
seed: 42
batch_size: 1
num_workers: 4
model_name: "unet"
max_epochs: 20
image_size: 224
learning_rate: 3e-4
use_scheduler: true

logs_dir: logs
checkpoint_dirpath: artifacts/checkpoints
