# data:
# one of list : “Task01_BrainTumour”, “Task02_Heart”, 
# “Task03_Liver”, “Task04_Hippocampus”, “Task05_Prostate”, 
# “Task06_Lung”, “Task07_Pancreas”, “Task08_HepaticVessel”,
#  “Task09_Spleen”, “Task10_Colon”.
task: “Task06_Lung”

# experiment:
seed: 42
batch_size: 128
num_workers: 32
use_class_weighting: true
use_weighted_sampler: false  # class weighting and weighted sampler are mutually exclusive
model_name: "densenet169"
max_epochs: 20
image_size: 224
learning_rate: 3e-4
use_scheduler: true

logs_dir: logs
checkpoint_dirpath: artifacts/checkpoints